# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-06-26 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('PermissionName', models.CharField(max_length=32)),
                ('Description', models.CharField(max_length=128)),
                ('Url', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='PerToRole',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('RoleId', models.IntegerField()),
                ('PerId', models.IntegerField()),
            ],
            options={
                'db_table': 'PerToRole',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=32)),
                ('Description', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='RoleToUser',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('RoleId', models.IntegerField()),
            ],
            options={
                'db_table': 'RoleToUser',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=32)),
                ('RealName', models.CharField(max_length=32)),
                ('PassWord', models.CharField(max_length=32)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('CreateTime', models.DateTimeField(default=datetime.datetime(2019, 6, 26, 10, 56, 34, 216201))),
                ('LastLogin', models.DateTimeField(default=datetime.datetime(2019, 6, 26, 10, 56, 34, 216201))),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
    ]
